sudo: required
services:
  - docker

before_install:
  - docker build -t pietrofxq/docker-complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pietrofxq/docker-complex-test npm test -- --coverage

after_success:
  - docker build -t pietrofxq/docker-complex-client ./client
  - docker build -t pietrofxq/docker-complex-server ./server
  - docker build -t pietrofxq/docker-complex-worker ./worker
  - docker build -t pietrofxq/docker-complex-nginx ./nginx
  # Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push pietrofxq/docker-complex-client
  - docker push pietrofxq/docker-complex-server
  - docker push pietrofxq/docker-complex-worker
  - docker push pietrofxq/docker-complex-nginx
